### ISSUE TITLE
Ahhh i see

### ISSUE THREAD

**Issue by nortxort** [notnola/TcRTC#1]
Okay, first off thanks for creating the example. After looking through your code, i realized  that the problem i had was related to me using single quotes for the connect message, or so i think anyway. Once this was sorted out and i could make a connection, i then created a class TinychatWebRTCClient using the same structure as pinylib.  At this point i am now able to send messages and also respond to ping's. The user class from pinylib could be used for this project, with relative few changes.

**Comment by NawtJ0sh** [comment]
@nortxort Hey Nort, are you planing on making a new client for ezcapechat...? I liked that you did when they were using flash.
